//
//  TransferReceiptViewModel.swift
//  BankingApp
//
//  ViewModel for Transfer Receipt screen showing completion details.
//  Story 4.5: Implement Transfer Receipt View
//

import Foundation
import Combine
import OSLog
import UIKit

final class TransferReceiptViewModel: ObservableObject {
    // MARK: - Published Properties

    @Published var transfer: Transfer?
    @Published var isLoading = false
    @Published var error: Error?
    @Published var showCopiedToast = false

    // MARK: - Properties

    let transferId: String

    // MARK: - Dependencies

    private let transferService: TransferServiceProtocol
    weak var coordinator: TransferCoordinator?

    // MARK: - Initialization

    init(
        transferId: String,
        transferService: TransferServiceProtocol,
        coordinator: TransferCoordinator?
    ) {
        self.transferId = transferId
        self.transferService = transferService
        self.coordinator = coordinator
    }

    // MARK: - Public Methods

    @MainActor
    func loadData() async {
        isLoading = true
        error = nil
        defer { isLoading = false }

        do {
            transfer = try await transferService.fetchTransfer(id: transferId)

            #if DEBUG
            Logger.transfer.debug("Loaded transfer receipt: \(self.transferId)")
            #endif
        } catch {
            self.error = error
            Logger.transfer.error("Failed to load transfer: \(error.localizedDescription)")
        }
    }

    func downloadReceipt() {
        guard let transfer = transfer else { return }

        let receiptText = formatReceiptText(transfer)
        coordinator?.presentShareSheet(text: receiptText)

        #if DEBUG
        Logger.transfer.debug("Sharing receipt for transfer: \(transfer.reference)")
        #endif
    }

    func copyReference() {
        guard let transfer = transfer else { return }
        UIPasteboard.general.string = transfer.reference
        showCopiedToast = true

        // Hide toast after 2 seconds
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
            self?.showCopiedToast = false
        }

        #if DEBUG
        Logger.transfer.debug("Copied reference to clipboard: \(transfer.reference)")
        #endif
    }

    // MARK: - Navigation

    func navigateToHome() {
        coordinator?.navigateToHome()
    }

    func navigateToAccounts() {
        coordinator?.navigateToAccounts()
    }

    // MARK: - Private Methods

    private func formatReceiptText(_ transfer: Transfer) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long
        dateFormatter.timeStyle = .short

        var receipt = """
        Transfer Receipt
        ================

        Reference: \(transfer.reference)

        From: \(transfer.sourceAccountName ?? "Account")
        To: \(transfer.destinationName)
        Amount: \(transfer.amount.formatted(currency: transfer.currency))
        Date: \(dateFormatter.string(from: transfer.date))
        Status: \(transfer.status.displayName)
        """

        if !transfer.description.isEmpty {
            receipt += "\n\nDescription: \(transfer.description)"
        }

        receipt += "\n\n---\nGenerated by BankingApp"

        return receipt
    }
}
